import type { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/navbar'

const notoSans = Noto_Sans({
	preload: true,
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${notoSans} antialiased`}>
				<Navbar />
				{children}
			</body>
		</html>
	)
}
